### ISSUE TITLE
Runner's user story

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/love-running#2]
In order to **track my running progress** as a **runner**, I can **set up an account that allows me to track my running progress**

## Acceptance Criteria:

* The website allows me to log in my running data, such as distance, time, and pace.
* The website displays my running progress in a clear and easy-to-understand format.
* The website allows me to set and track my running goals, such as running a specific distance or specific race.

## Tasks

- [ ] Create a running data model in the websites's database'
- [ ] Develop a running data entry form for users to input their running data
- [ ] Create a running progress dashboard to display users's running progress.
