### ISSUE TITLE
Anonymous feedback as a User

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/love-running#4]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

## Acceptance Criteria:

* The option should be provided as a checkbox.
* The checkbox should be "checked" by default.
* The option should appear next to the submit button

## Tasks

- [ ] Update the view: the poll design to include the checkbox and to show the name of submitter.
- [ ] Create a new field in the model to track the username.
- [ ] Update the controller function.
